### ISSUE TITLE
Old vulnerable copy of uriparser 0.8.6, please update

### ISSUE THREAD

**Issue by hartwork** [nextgis-borsch/lib_uriparser#1]
Hi,

it came to my attention that you bundle vulnerable uriparser 0.8.6 here. Please consider updating to [version 0.9.2](https://github.com/uriparser/uriparser/releases/tag/uriparser-0.9.2). Thank you!

Best, Sebastian

**Comment by BishopGIS** [comment]
Fixed per 82ca604b7a7c140d34fb24845969156fe89fad26
Thanks!

**Comment by hartwork** [comment]
Thanks!
